name: Building and testing on push
on: [push]
jobs:
  build:
    name: Build
    runs-on: Linux
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: ./.github/actions/gem5-dev/
        with:
          script-path: '.github/scripts/build-test.sh'
      
